service: traveller-back-service

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2

functions:
  tasks:
    handler: traveller.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: traveller/blog
          method: get
          cors: true
      - http:
          path: traveller/user
          method: get
          cors: true
      - http:
          path: traveller/user
          method: post
          cors: true
      - http:
          path: traveller/blog
          method: post
          cors: true
      - http:
          path: traveller/{id}
          method: delete
          cors: true
      - http:
          path: traveller
          method: put
          cors: true
